DELETE 

FROM SEGMERCADO

WHERE ID =10000;
-------------------------------------------------
SELECT * FROM SEGMERCADO;

DECLARE
v_ID        SEGMERCADO.ID%TYPE          := 10000;
v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE   := 'Varejo';
BEGIN
INSERT INTO SEGMERCADO (SEGMERCADO.ID, SEGMERCADO.DESCRICAO) VALUES (v_ID,v_DESCRICAO);
COMMIT;
END;
--------------------------------------------------

-- obrigar a escrita correta no imput de dados
-- primeira maiuscula e o resto minusculo (INITCAP)

SELECT * FROM SEGMERCADO;

DECLARE
v_ID        SEGMERCADO.ID%TYPE          := 20000;
v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE   := 'COMERCIO';
BEGIN
INSERT INTO SEGMERCADO (SEGMERCADO.ID, SEGMERCADO.DESCRICAO) VALUES (v_ID,INITCAP(v_DESCRICAO));
COMMIT;
END;

--------------------------------------
-- USANDO O MESMO BLOCO PARA VARIOS COMANDOS APEAS ALTERANDOAS VARIAVEIS

DECLARE
v_ID        SEGMERCADO.ID%TYPE          := 10000;
v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE   := 'VAREJISTA';

BEGIN
UPDATE SEGMERCADO SET DESCRICAO = INITCAP(v_DESCRICAO) WHERE SEGMERCADO.ID = v_ID;

--ALTERANDO AS VARIAVEIS
v_ID  := 10001;
v_DESCRICAO:= 'ATACADISTA';
UPDATE SEGMERCADO SET DESCRICAO = INITCAP(v_DESCRICAO) WHERE SEGMERCADO.ID = v_ID;

v_ID := 10002;
v_DESCRICAO:= 'INDUSTRIAL';
UPDATE SEGMERCADO SET DESCRICAO = INITCAP(v_DESCRICAO) WHERE SEGMERCADO.ID = v_ID;

v_ID := 10003;
v_DESCRICAO := 'LABORATORIAL';
UPDATE SEGMERCADO SET DESCRICAO = INITCAP(v_DESCRICAO) WHERE SEGMERCADO.ID = v_ID;
COMMIT;
END;

-------------------------------------------------------------------------------------------

SELECT * FROM PRODUTO_EXERCICIO;


DECLARE
v_COD       PRODUTO_EXERCICIO.COD%TYPE := 67120;
v_DESCRICAO PRODUTO_EXERCICIO.DESCRICAO%TYPE :=  'Frescor da Montanha - Aroma Limão - 1 Litro';
v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE := 'AGUA';

BEGIN

INSERT INTO PRODUTO_EXERCICIO (COD, DESCRICAO,CATEGORIA) VALUES (v_COD, INITCAP(v_DESCRICAO),INITCAP(v_CATEGORIA));
COMMIT;

UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(v_DESCRICAO,'-','>') WHERE COD = v_COD;


v_COD       := 41232;
v_DESCRICAO :='Sabor de Verão - Laranja - 1 Litro';
v_CATEGORIA := 'Sucos de Frutas';
UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(v_DESCRICAO,'-','>')  WHERE COD = v_COD;

v_COD       := 32223;
v_DESCRICAO :='Sabor de Verão - Uva - 1 Litro';
v_CATEGORIA := 'Sucos de Frutas';
UPDATE PRODUTO_EXERCICIO SET DESCRICAO = REPLACE(v_DESCRICAO,'-','>')  WHERE COD = v_COD;
COMMIT;
END;
---------------------------------------------------------------------------------------------

/*  Execute o script abaixo para incluir mais um produto:
    Depois, faça um script em PL/SQL que altere a categoria de um produto, 
    passando como variáveis iniciais o COD e o novo valor para CATEGORIA .
    Mude o produto incluído acima de Águas para Mate .*/
    
DECLARE 

v_COD       PRODUTO_EXERCICIO.COD%TYPE ;
v_DESCRICAO PRODUTO_EXERCICIO.DESCRICAO%TYPE ;
v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE ;

BEGIN
v_COD := '92347';
v_DESCRICAO := 'Aroma do Campo - Mate - 1 Litro';
v_CATEGORIA := 'Águas';

INSERT INTO PRODUTO_EXERCICIO (COD,DESCRICAO,CATEGORIA) VALUES (v_COD, INITCAP(v_DESCRICAO), INITCAP(v_CATEGORIA));
COMMIT;
END;

---
DECLARE 

v_COD       PRODUTO_EXERCICIO.COD%TYPE := '92347' ;
v_CATEGORIA PRODUTO_EXERCICIO.CATEGORIA%TYPE := 'MATE' ;
BEGIN
UPDATE PRODUTO_EXERCICIO SET CATEGORIA = INITCAP(v_CATEGORIA) WHERE PRODUTO_EXERCICIO.COD = v_COD;
COMMIT;
END;
-----------------------------------------------------------------------------