SET SERVEROUTPUT ON;
DECLARE
    v_ID        SEGMERCADO.ID%TYPE   := 10003;
    v_DESCRICAO SEGMERCADO.DESCRICAO%TYPE ;
BEGIN
    SELECT DESCRICAO INTO v_DESCRICAO FROM SEGMERCADO WHERE ID = v_ID;
    DBMS_OUTPUT.PUT_LINE(v_DESCRICAO);
END;    