SELECT * FROM TB_VENDEDORES;

UPDATE TB_VENDEDORES SET NOME = 'CARLOS SILVA MOREIRA'

WHERE MATRICULA = 414;

UPDATE TB_VENDEDORES SET PERCEN_COMIS = 19
WHERE 
MATRICULA = 414 ;

UPDATE TB_VENDEDORES SET PERCEN_COMIS = 19
WHERE 
MATRICULA = 400;

/*----------------------------------------*/

SELECT * FROM  TB_PRODUTOS;

UPDATE TB_PRODUTOS SET NOME_PDT = 'SKOL', TAMANHO = '650 ML',
SABOR = 'CERVEJA',PRECO_LIST = 12.11
WHERE
PRODUTO = '12345';
/*----------------------------------------*/
UPDATE TB_CLIENTES SET NOME = 'Pedrinho Pedra Pedregulho',  ENDERECO = 'Rua Terra Batida'
where
cpf = '76504534565';
