CREATE TABLE TB_VENDEDORES (
MATRICULA number(5,0) ,
NOME VARCHAR2 (100),
DATA_ADMISSAO DATE,
PERCEN_COMIS NUMBER (2)

)

CREATE TABLE TB_CLIENTES(
CPF VARCHAR2(11),
NOME VARCHAR2(100),
ENDERECO VARCHAR2 (120),
NUM_END VARCHAR2 (6),
CEP NUMBER (8),
CIDADE VARCHAR2 (15),
ESTADO VARCHAR2 (15),
NACIONALIDADE varchar2(100) default NULL,
DAT_NASC DATE,
PRIM_COMPRA NUMBER(1),
LIM_CRED NUMBER (15,2)

)

/*-------------------------*/
ALTER TABLE TB_VENDEDORES

MODIFY COLUMN PERCEN_COMIS NUMBER (0.2);

DROP TABLE TB_CLIENTES;

/*-------------------------*/

ALTER TABLE TB_CLIENTES

MODIFY COLUMN NUM_END INT ;


