-- CHAVES ESTRANGEIRAS NÃO PRECISAM TER OS MESMOS NOMES , MAS PRECISAM SER DO MESMO TIPO (NUMBER=NUMBER) OU (VARCHAR=VARCHAR), ETC.


--TABELA PARA O CURSO 3

CREATE TABLE SEGMERCADO (
ID          NUMBER (5,0) PRIMARY KEY,
DESCRICAO   VARCHAR2 (100)
);


CREATE TABLE CLIENTE (
ID              NUMBER(5),
RAZAO_SOCIAL    VARCHAR2(100),
CNPJ            VARCHAR2(20),
SEGMERCADO      NUMBER(5),
DAT_INCLUSAO    DATE,
FAT_PREVISTO    NUMBER(10,2),
CATEGORIA        VARCHAR2(20)
) ;

--CRIANDO OS VINCULOS DE CHAVES PK E FK
ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_ID_PK /*NOME DA RESTRIÇÃO (CONSTRAINT)*/
PRIMARY KEY (ID);

ALTER TABLE CLIENTE ADD CONSTRAINT CLIENTE_SEGMERCADO_FK
FOREIGN KEY (SEGMERCADO) REFERENCES SEGMERCADO (ID);

--------------
create TABLE PRODUTO_EXERCICIO (
COD         VARCHAR2(5) PRIMARY KEY,
DESCRICAO   VARCHAR2(100),
CATEGORIA    VARCHAR2(100)
);

CREATE TABLE PRODUTO_VENDA_EXERCICIO (
ID          NUMBER(5) PRIMARY KEY,
COD_PRODUTO VARCHAR2(5),
DATA        DATE,
QUANTIDADE  FLOAT,
PRECO       FLOAT,
VALOR_TOTAL FLOAT,
PERCENTUAL_IMPOSTO FLOAT
);

ALTER TABLE PRODUTO_VENDA_EXERCICIO 
ADD CONSTRAINT PRODUTO_VENDA_EXERCICIO_COD_PRODUTO_FK
FOREIGN KEY (COD_PRODUTO) 
REFERENCES PRODUTO_EXERCICIO (COD);


