INSERT INTO TB_PRODUTOS(
PRODUTO , NOME_PDT , EMBALAGEM , TAMANHO , SABOR , PRECO_LIST
)
VALUES
('1856','FANTA', 'PET', '2 LTS', 'LARANJA', 7.34);
INSERT INTO TB_PRODUTOS(
PRODUTO , NOME_PDT , EMBALAGEM , TAMANHO , SABOR , PRECO_LIST
)
VALUES
('12345','SPRITE', 'PET', '2 LTS', 'LIMAO', 8.14);

INSERT INTO TB_PRODUTOS(
PRODUTO , NOME_PDT , EMBALAGEM , TAMANHO , SABOR , PRECO_LIST
)
VALUES
('10797', 'Clean', 'PET', '2 LTS' ,'Laranja',16,01);


SELECT * FROM tb_produtos;

/*-----------------------------------------------------*/
INSERT INTO TB_VENDEDORES  (
MATRICULA , NOME, DATA_ADMISSAO, PERCEN_COMIS
)
VALUES
(234, 'EDICLEUSA PINTO SUNSUARANA', '24/03/2020',10);

INSERT INTO tb_vendedores(
MATRICULA , NOME , DATA_ADMISSAO, PERCEN_COMIS
)
VALUES
(0400,	'MARIA DO ROSARIO',	'23/07/2012',	15)

INSERT INTO tb_vendedores(
MATRICULA , NOME , DATA_ADMISSAO, PERCEN_COMIS
)
VALUES
(00810,	'MARCIA ALMEIDA',	'14/12/2016', 18);

INSERT INTO tb_vendedores(
MATRICULA , NOME , DATA_ADMISSAO, PERCEN_COMIS
)
VALUES
(00414,	'Carlos Moreira','13/11/2015', 14);

INSERT INTO tb_vendedores(
MATRICULA , NOME , DATA_ADMISSAO, PERCEN_COMIS
)
VALUES
(00934,	'JUVENILDO JUVENTUS JUNIOR', '09/03/2010', 20);

INSERT INTO TB_VENDEDORES (
MATRICULA , NOME, DATA_ADMISSAO, PERCEN_COMIS
)VALUES (
00265 , 'Jonh Wayne',TO_DATE('03/27/2019','MM/DD/YYYY'),17 
);

INSERT INTO TB_VENDEDORES (MATRICULA , NOME, DATA_ADMISSAO, PERCEN_COMIS
)VALUES (
00777,'Katy Peterson', TO_DATE('02/04/2020','MM/DD/YYYY'),10);

INSERT INTO TB_VENDEDORES (MATRICULA , NOME, DATA_ADMISSAO, PERCEN_COMIS
)VALUES (
00342,'Rodrigo Almeida','18/01/2022',9);

SELECT * FROM TB_VENDEDORES;

SELECT TO_CHAR(DATA_ADMISSAO, 'MM')FROM TB_VENDEDORES;

/*-----------------------------------------------------*/

INSERT INTO TB_CLIENTES
(CPF,NOME,ENDERECO,NUM_END,CEP,CIDADE,ESTADO,NACIONALIDADE,DAT_NASC,PRIM_COMPRA,
LIM_CRED)
VALUES
('7504534565','PEDRINHO PEDR PINTO','RUA DE TERRA BATIDA',6969,3456000,'SEILANDIA',
'SP','BRASILEIRO','12/12/1912',1,6000);

INSERT INTO TB_CLIENTES 
(CPF,NOME,ENDERECO,NUM_END,CEP,CIDADE,ESTADO,NACIONALIDADE,DAT_NASC,PRIM_COMPRA,
LIM_CRED)
VALUES
('12398722340','Oscar Olino Olario','Rua Tenente Tinino',34723,45672000,'São Paulo',
'SP','Brasileiro', TO_DATE('02/06/1977','DD/MM/YYYY'),0,3000.50);

select * from TB_CLIENTES;

SELECT TO_CHAR(DAT_NASC,'MM') FROM TB_CLIENTES;


