
------- CRIAR FILTRO PARA VALIDAR O VOLUME MAXIMO DE COMPRAS DOS CLIENTES -----------

-- PASSO 1 >> TABELA BASE DO CLIENTE
SELECT TABCLI.NOME, TABCLI.CPF, TABCLI.VOLUME_DE_COMPRA FROM TABELA_DE_CLIENTES TABCLI;

--PASSO 2 >> CRIAR AMARRAÇAO VOLUMETRIA MENSAL
SELECT NFS.CPF, TO_CHAR(NFS.DATA_VENDA,'MM/YYYY') AS MES_ANO ,SUM( ITNF.QUANTIDADE) AS VALOR_MENSAL  
FROM NOTAS_FISCAIS NFS
INNER JOIN
ITENS_NOTAS_FISCAIS ITNF
ON NFS.NUMERO = ITNF.NUMERO
GROUP BY NFS.CPF , TO_CHAR(NFS.DATA_VENDA,'MM/YYYY')
ORDER BY NFS.CPF;

-- PASSO 3 >> JUNTAR AS DUAS QUERY

SELECT TABCLI.NOME, TABCLI.CPF, TABCLI.VOLUME_DE_COMPRA , VOL_MENSAL.QTD_TOTAL , VOL_MENSAL.MES_ANO
FROM 
TABELA_DE_CLIENTES TABCLI
INNER JOIN
(SELECT NFS.CPF, TO_CHAR(NFS.DATA_VENDA,'MM/YYYY') AS MES_ANO ,SUM( ITNF.QUANTIDADE) AS QTD_TOTAL  
FROM NOTAS_FISCAIS NFS
INNER JOIN
ITENS_NOTAS_FISCAIS ITNF
ON NFS.NUMERO = ITNF.NUMERO
GROUP BY NFS.CPF , TO_CHAR(NFS.DATA_VENDA,'MM/YYYY')
) VOL_MENSAL
ON TABCLI.CPF = VOL_MENSAL.CPF
ORDER BY TABCLI.NOME;

--PASSO 4 >> ADICIONAR UM CASE WHEN

SELECT TABCLI.NOME, TABCLI.CPF, TABCLI.VOLUME_DE_COMPRA , VOL_MENSAL.QTD_TOTAL , VOL_MENSAL.MES_ANO,
(CASE
WHEN VOL_MENSAL.QTD_TOTAL > TABCLI.VOLUME_DE_COMPRA THEN 'ULTRAPASSOU O LIMITE MENSAL'
ELSE 'DENTRO DO LIMITE'
END) AS METRICA
FROM 
TABELA_DE_CLIENTES TABCLI
INNER JOIN
(SELECT NFS.CPF, TO_CHAR(NFS.DATA_VENDA,'MM/YYYY') AS MES_ANO ,SUM( ITNF.QUANTIDADE) AS QTD_TOTAL  
FROM NOTAS_FISCAIS NFS
INNER JOIN
ITENS_NOTAS_FISCAIS ITNF
ON NFS.NUMERO = ITNF.NUMERO
GROUP BY NFS.CPF , TO_CHAR(NFS.DATA_VENDA,'MM/YYYY')
) VOL_MENSAL
ON TABCLI.CPF = VOL_MENSAL.CPF
ORDER BY TABCLI.NOME;

--PASSO 4 ADICIONAR FILTROS PARA DESTACAR QUEM PASSOU E A DIFERENÇA ENTRE O PERMITIDO
        -- USANTO (1 - (TC.VOLUME_DE_COMPRA/TV.QUANTIDADE_TOTAL)) * 100 PAARA A PORCENTAGEM

SELECT TABCLI.NOME, TABCLI.CPF, FORMULA_MENSAL.MES_ANO, TABCLI.VOLUME_DE_COMPRA , FORMULA_MENSAL.QTD_TOT_MES,

ROUND((1 - (TABCLI.VOLUME_DE_COMPRA/FORMULA_MENSAL.QTD_TOT_MES)) * 100)  || ' %'AS PORCENTEGEM,

(CASE
WHEN FORMULA_MENSAL.QTD_TOT_MES > TABCLI.VOLUME_DE_COMPRA THEN 'FORA DO LIMITE'
ELSE 'DENTRO DO LIMITE'
END) AS METRICA

FROM TABELA_DE_CLIENTES TABCLI
INNER JOIN
(SELECT NFS.CPF, TO_CHAR(NFS.DATA_VENDA,'MM/YYYY') AS MES_ANO , SUM(ITNF.QUANTIDADE) AS QTD_TOT_MES
FROM NOTAS_FISCAIS NFS
INNER JOIN
ITENS_NOTAS_FISCAIS ITNF
ON NFS.NUMERO = ITNF.NUMERO
GROUP BY NFS.CPF, TO_CHAR(NFS.DATA_VENDA,'MM/YYYY')) FORMULA_MENSAL
ON TABCLI.CPF = FORMULA_MENSAL.CPF
WHERE
(FORMULA_MENSAL.QTD_TOT_MES - TABCLI.VOLUME_DE_COMPRA) > 0 ;

