ALTER TABLE TB_VENDEDORES
/*ADICIONAR UMA RESTRIÇÃO = CONSTRAINT*/
ADD CONSTRAINT PK_TB_VENDEDORES

PRIMARY KEY(MATRICULA);



SELECT * FROM TB_VENDEDORES;

/*-------------------------*/
ALTER TABLE TB_CLIENTES

ADD CONSTRAINT PK_TB_CLIENTES

PRIMARY KEY (CPF);

SELECT * FROM TB_CLIENTES